version: "2.2"
services:
  jobmanager:
    image: flink:1.12.1-scala_2.12
    ports:
      - "8081:8081"
    command: standalone-job --job-classname com.trendyol.batch.BatchJob --input-file /input/case.csv --output-path /output
    volumes:
      - ./target/scala-2.12:/opt/flink/usrlib
      - ./input:/input
      - ./output:/output
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    image: flink:1.12.1-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./target/scala-2.12:/opt/flink/usrlib
      - ./input:/input
      - ./output:/output
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
